export const homepageSeoQuery = `*[_type == "homepage"][0]{
  _id,
  _type,
  seo{
    title,
    description,
    ogImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions{
            width,
            height
          }
        }
      },
      alt,
      hotspot,
      crop
    },
    keywords,
    canonicalUrl,
    twitterHandle,
    linkedInHandle,
    behanceHandle,
    instagramHandle
  }
}`;

export const homepageContentQuery = `*[_type == "homepage"][0]{
  _id,
  _type,
  hero{
    centerPieceImage{
      asset->{
        _id,
        url,
        metadata{
          dimensions{
            width,
            height
          }
        }
      },
      alt,
      hotspot,
      crop
    },
    beforeTypewriterText,
    typewriterWords,
    remainingText,
    subHeading,
    hireLink{
      text,
      url
    },
    cvLink{
      text,
      externalUrl
    }
  },
  experiences[]{
    jobTitle,
    organisationLogo{
      asset->{
        _id,
        url,
        metadata{
          dimensions{
            width,
            height
          }
        }
      },
      alt,
      hotspot,
      crop
    },
    duration,
    description,
    order
  } | order(order asc),
  beyondPortfolio{
    currentBook{
      description,
      bookImage{
        asset->{
          _id,
          url,
          metadata{
            dimensions{
              width,
              height
            }
          }
        },
        alt,
        hotspot,
        crop
      },
      popupContent
    },
    techStack{
      heading,
      tools[]{
        logo{
          asset->{
            _id,
            url,
            metadata{
              dimensions{
                width,
                height
              }
            }
          },
          hotspot,
          crop
        },
        alt,
        name
      },
      popupContent
    },
    collaborators{
      heading,
      avatars[]{
        avatar{
          asset->{
            _id,
            url,
            metadata{
              dimensions{
                width,
                height
              }
            }
          },
          hotspot,
          crop
        },
        alt,
        name
      },
      popupContent
    },
    persona{
      heading,
      personaItems,
      popupContent
    },
    recentWork{
      heading,
      workImage{
        asset->{
          _id,
          url,
          metadata{
            dimensions{
              width,
              height
            }
          }
        },
        alt,
        hotspot,
        crop
      },
      popupContent
    }
  },
  testimonials[]{
    name,
    avatar{
      asset->{
        _id,
        url,
        metadata{
          dimensions{
            width,
            height
          }
        }
      },
      alt,
      hotspot,
      crop
    },
    position,
    testimony,
    rating,
    order
  } | order(order asc)
}`;
